Server coin
Datalayer-Storage/DataLayer-Driver pull request #4
Opened 2024-08-31 00:02 UTC by Rigidity

2024-08-31 07:03 UTC, Yakuhito commented on src/server_coin.rs
> +    b10ce2d0b18dcf8c21ddfaf55d9b9f0adcbf1e0beb55b1a8b9cad9bbff4e5f22
I assume this is correct

2024-08-31 07:08 UTC, Yakuhito requested changes
Good stuff! Please also make a note of the breaking changes like [here](https://github.com/Datalayer-Storage/DataLayer-Driver/pull/3) so MT has an easier time migrating.

Also, update README.md to include the new functions  :)

2024-09-02 16:03 UTC, Rigidity commented on src/server_coin.rs
> +    b10ce2d0b18dcf8c21ddfaf55d9b9f0adcbf1e0beb55b1a8b9cad9bbff4e5f22
Yes, added a test

2024-09-02 16:05 UTC, Yakuhito commented on src/server_coin.rs
> +    b10ce2d0b18dcf8c21ddfaf55d9b9f0adcbf1e0beb55b1a8b9cad9bbff4e5f22
many tanks

2024-09-02 16:07 UTC, Rigidity commented
> Good stuff! Please also make a note of the breaking changes like [here](https://github.com/Datalayer-Storage/DataLayer-Driver/pull/3) so MT has an easier time migrating.
> 
> Also, update README.md to include the new functions :)

There shouldn't be any breaking changes

2024-09-02 16:08 UTC, Yakuhito approved these changes

2024-09-02 16:56 UTC, merged